// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCM4V1iGaZ1TVqtU3yZJgBsFJBaX33LVx0',
    appId: '1:271224890891:web:8452ae8967e2e73c44490e',
    messagingSenderId: '271224890891',
    projectId: 'appwellq',
    authDomain: 'appwellq.firebaseapp.com',
    storageBucket: 'appwellq.firebasestorage.app',
    measurementId: 'G-J7E22C2DFL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMlrDPaME_-q7tLqFVrafROkpbvckbkZA',
    appId: '1:271224890891:android:3f6072071500234744490e',
    messagingSenderId: '271224890891',
    projectId: 'appwellq',
    storageBucket: 'appwellq.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-PtUkQlPqSUg5zRS0O6mhXaysTpgJaF0',
    appId: '1:271224890891:ios:c71198935e25a21644490e',
    messagingSenderId: '271224890891',
    projectId: 'appwellq',
    storageBucket: 'appwellq.firebasestorage.app',
    iosBundleId: 'com.example.app_wellq',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-PtUkQlPqSUg5zRS0O6mhXaysTpgJaF0',
    appId: '1:271224890891:ios:c71198935e25a21644490e',
    messagingSenderId: '271224890891',
    projectId: 'appwellq',
    storageBucket: 'appwellq.firebasestorage.app',
    iosBundleId: 'com.example.app_wellq',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCM4V1iGaZ1TVqtU3yZJgBsFJBaX33LVx0',
    appId: '1:271224890891:web:06c8d1850bc39eef44490e',
    messagingSenderId: '271224890891',
    projectId: 'appwellq',
    authDomain: 'appwellq.firebaseapp.com',
    storageBucket: 'appwellq.firebasestorage.app',
    measurementId: 'G-7H4KTHQY7S',
  );
}
